version: '3'

services:

  php_triple:
    container_name: neayi_php
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/:rw
    depends_on:
      - mysql_triple
    networks:
      - front-tier
      - back-tier

  mysql_triple:
    container_name: neayi_mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: cnpg
      MYSQL_USER: cnpg
      MYSQL_PASSWORD: abc
      MYSQL_ROOT_PASSWORD: abc
    ports:
      - 3306:3306
    networks:
      - back-tier

  nginx_triple:
    container_name: neayi_nginx
    image: nginx:1.15.8
    ports:
      - 8008:80
    volumes:
      - ./:/var/www/html/
      - ./cnpg.conf:/etc/nginx/conf.d/cnpg.conf
    networks:
      - back-tier
      - front-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  php_triple:
  mysql_triple:
